volumes:
  node_modules:
services:
  fcw-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "80:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
