# --- Base Stage ---
FROM node:22.14 AS base
ENV NODE_ENV=development
WORKDIR /src

# --- Build Stage ---
FROM base AS build
COPY package.json package-lock.json ./
RUN npm ci

# --- Run Stage ---
FROM base AS development
COPY --from=build /src/node_modules /src/node_modules
CMD [ "npm", "run", "dev" ]
